export const itemNames = [
    "Alien Cranium", "Altruist's Adornment", "Anger", "Ap-Sap", "Aperture Labs Hard Hat", 
    "Apoco-Fists", "Archimedes", "Area 451", "Arkham Cowl", "Asymmetric Accolade", 
    "Atomic Accolade", "Audio File", "Auspicious Automaton Assembler's Accolade", 
    "Awesomenauts Badge", "AWPer Hand", "Backbiter's Billycock", "Ball-Kicking Boots", 
    "Balloonicorn", "Baronial Badge", "Battle Bob", "Beastly Bonnet", "Big Daddy", 
    "Biomech Backpack", "Blind Justice", "Boiling Point", "Bolgan", "Bolgan Family Crest", 
    "Bonk Helm", "Brain Bucket", "Brigade Helm", "Brimstone", "Brütal Bouffant", 
    "Buck Turner All-Stars", "Bushman's Boonie", "Camera Beard", "Centurion", 
    "Champ Stamp", "Cheet Sheet", "Chief Constable", "Cockfighter", "Cold War Luchador", 
    "Combat Medic's Crusher Cap", "Companion Cube Pin", "Company Man", "Concheror", 
    "Conjurer's Cowl", "Conniver's Kunai", "Conspiracy Cap", "Crafty Hair", 
    "Criminal Cloak", "Croft's Crest", "Cross-Comm Crash Helmet", "Cross-Comm Express", 
    "Crosslinker's Coil", "Crown of the Old Kingdom", "Dadliest Catch", 
    "Dashin' Hashshashin", "Dead Cone", "Deadliest Duckling", 
    "Der Maschinensoldaten-Helm", "Deus Specs", "Diamondback", 
    "Die Regime-Panzerung", "Distinguished Rogue", "Doe-Boy", "Doublecross-Comm", 
    "Dragonborn Helmet", "Dread Hiding Hood", "Dread Knot", "El Jefe", "Engineer's Cap", 
    "Faerie Solitaire Pin", "Fan O'War", "Fear Monger", "Firefly", "First American", 
    "Flying Guillotine", "Foppish Physician", "Fortified Compound", "Fortune Hunter", 
    "Freedom Staff", "Friends Forever Companion Square Badge", "Geisha Boy", 
    "Gilded Guard", "Glengarry Bonnet", "Grandmaster", "Grizzled Growth", "Half-Zatoichi", 
    "Ham Shank", "Hardy Laurel", "Heavy Artillery Officer's Cap", "Hero's Hachimaki", 
    "Hero's Tail", "Heroic Companion Badge", "Hetman's Headpiece", "Hitt Mann Badge", 
    "Horace", "Human Cannonball", "Huo-Long Heater", "InfoShow TF2 Tournament Participant", 
    "Janissary Ketche", "Jungle Booty", "K-9 Mane", "Killer Exclusive", 
    "King of Scotland Cape", "Lacking Moral Fiber Mask", "Last Straw", "Little Bear", 
    "Lone Star", "Machina", "Map Maker's Medallion", "Mappers vs. Machines Participant Medal 2017", 
    "Mark of the Saint", "Marxman", "Mask of the Shaman", "Master's Yellow Belt", "Maul", 
    "Menpo", "Merc Medal", "Merc's Pride Scarf", "Mister Bubbles", "MK 50", "Nabler", 
    "Nanobalaclava", "Neon Annihilator", "Noh Mercy", "Noise Maker", 
    "Nostromo Napalmer", "Officer's Ushanka", "Original", "Otolaryngologist's Mirror", 
    "Person in the Iron Mask", "Philanthropist's Indulgence", "Pilotka", "Pip-Boy", 
    "Planeswalker Goggles", "Planeswalker Helm", "Point and Shoot", "Potato of Labor", 
    "Pounding Father", "Prinny Hat", "Prinny Machete", "Prinny Pouch", "Prize Plushy", 
    "Professional's Panama", "Professor's Pineapple", "Public Accessor", "Purity Fist", 
    "Quadwrangler", "Quäckenbirdt", "Red-Tape Recorder", "Respectless Rubber Glove", 
    "Righteous Bison", "Robo-Sandvich", "Robot Chicken Hat", "Russian Rocketeer", 
    "Samur-Eye", "Scotsman's Stove Pipe", "Scrap Pack", "Sharp Dresser", 
    "Sharpened Volcano Fragment", "Short Circuit", "Shred Alert", "Siberian Sophisticate", 
    "Sign of the Wolf's School", "Spycrab", "Stahlhelm", "Stainless Pot", 
    "Steel Sixpack", "Steel Songbird", "Stovepipe Sniper Shako", "Sun-on-a-Stick", 
    "Supreme Strategist's Sigil of Status", "Sydney Straw Boat", "Tartan Shade", 
    "Tartantaloons", "Texas Ten Gallon", "TF2VRH", "That '70s Chapeau", 
    "Three-Rune Blade", "Tomb Readers", "Tomb Wrapper", "Top Notch", 
    "Tough Guy's Toque"
];

// items.js
export const itemImageMap = {
    "Alien Cranium": "https://stntrading.eu/img/-vNDFTdk3-nYzDrWZkSQ4NWsAgIBhp8n5vhlfOPRUFA/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFS1pUZ1pXQnJtaHpSQ21zX2pRX1NKVUxoUW1ZdG10Y0VOMkdab2xGQWpON0hoWW1aaUkxZkFBX05ZRHFWam9sNjlDM1ZrNjhJdFJObXhlZjY4eFhV.webp",
    "Altruist's Adornment": "src/lib/assets/MissingItem.png",
    "Anger": "https://stntrading.eu/img/Lr9nP0I4mVBdmwyvkGoXnGMQbRtlKhU5L65gglssNzw/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV3VVVTU1RncWpGTmc4RHBBdmF6Qk9FU25OOTd2Y2hXZ0RNX3hRQXVOckh0TldNektnSEdCYVpkQmFJOHBWbTdESFpudVpGZ0I0T3o4YmdBTHhLdjZ0VnVFMXQwVUE.webp",
    "Ap-Sap": "https://stntrading.eu/img/Oz1_OU62LqL7cPntAy8WO_1l5do_9eu_tb2NuzCFvdM/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV4ZERUeDdoaHpSQ21zX2pRNmFORExBR21OdGw1TVpXZ1RWcHd3TXVNcmZzWm1NeGNBSEdWYVFJRHFJLTlRN3BVSGRrdUpFdFJObXhraldCb0s4.webp",
    "Aperture Labs Hard Hat": "src/lib/assets/MissingItem.png",
    "Apoco-Fists": "https://stntrading.eu/img/hvZXgvx5Mu5slxcmnhlnYR4lkxdyImfcogOZAadxTMQ/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV4UUREaVR5clRaQWdQZnFET0NMRGE0Rnc5eGtzNUlGaVRBN3h3Qi1iZWUwWWpZMGR3Q2FVYVpkV3FKanJWX29YU0ZsdUpjMEFZZmp1YXNJTHFueGV4d0Y.webp",
    "Archimedes": "https://stntrading.eu/img/lWBwhVSRR717ZQDqbeyVnh7u__2JMCb92i8nkTzoKIQ/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFS2ZnUVpWQmJudkQxUXQ4VG5IX1dKUnJVR3lOa3g1NU1OaVdVNXdWSXJiTFhqTWpGa0t3S1FVdk1NQ19adXBGcTVYSGRqdVpFeVVOUDQ1N1VCTzVaeFJuYw.webp",
    "Area 451": "https://stntrading.eu/img/IMdgkhrsLUXQYoLQO6b_zN6Oatxfo-EWSy6xzO3cNdU/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFVGJ3Z2NZZ2pudXl4TWdjelpBUE9mQTk4TW1zZ3k0TjRHaVdjLXdGZ3JZLVhsTVdRMEpGMlVCUGNMQ2FKcHJGLTVEU0podTU0d0JZSHZwcjVWS0ZxN3FzS1laRWFsTzhVYQ.webp",
    "Arkham Cowl": "https://stntrading.eu/img/qOlCIe2bZzgnCHqOZg7aaUOX8VZVuYZP3mcfmhEnU4s/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSmJRd3VYQW5wc0RsT3Q4dnBHdjZ6Qk9FU25OOTdzc05SMm1jLXhsWjVOZVhnWW00eEpRQ1dVS1FJRDZCcDhGcTdDQ1EydlpKZ1VJZnZwT0pmZXhLdjZ0V3pDQWI1TWc.webp",
    "Asymmetric Accolade": "src/lib/assets/MissingItem.png",
    "Atomic Accolade": "src/lib/assets/MissingItem.png",
    "Audio File": "https://stntrading.eu/img/eTCFaz3g344d8dDz-O_Z1AErBhBpqUd66RMJcjMRTiw/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFWVl4SWZXUV93dVR0SXQ4RG5HYzJBQ2ZJSG5wUXo1NVVEM0ROcGwxVl9aYkRpWTJCa0kxUEVVUFVKWGF4cHJWRy1DQ1Jrc1pWbkJJSHZvdTFWWjB5eDQ4MDV5SDVq.webp",
    "Auspicious Automaton Assembler's Accolade": "src/lib/assets/MissingItem.png",
    "Awesomenauts Badge": "src/lib/assets/MissingItem.png",
    "AWPer Hand": "https://stntrading.eu/img/o6Rw-yMeiiXBNPeRjRb6QPDDc8lFHJtD6D5Md3319xU/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV3UUNXaFRkdVM5VHQ4VG5IX1dKUnVKWnlvTXg1TU1NaTJGdGxWVXVaYmJsTTI5aEt3YVVCYVZZRGZSdW9WdTdEQ0l4dnNabVZvSDQ1N1VCRkxJU2Y5cw.webp",
    "Backbiter's Billycock": "https://stntrading.eu/img/M6Melwh0kfFe9Y43zStN82yHOzX7-6gxrgdEveim0_o/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFUGFSVVRSQ1RxdVN4OGhNbjBDdmZDV09ZR3pJbHM1NVlIM1dacXhnUWpadWJrTTI4eGN3S2FWdmtNV1BZODhWbnRXM2MwNmNZMEE1bW0tYnhTeHRhWFBR.webp",
    "Ball-Kicking Boots": "src/lib/assets/MissingItem.png",
    "Balloonicorn": "https://stntrading.eu/img/nFkpeRpThsSIYM8T7Goxf182dNP2vcLWsRtIiyxkWqA/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFYmFSTXVYeHJ1dERkTWhzSGxBdUNDTi13QmlkMHdxOGdOaVdNNWtGbDlacnJ0TW1jLUpRYVdCNllOREtVNzhsRy1DSEJxdnBRNkI0YTFyN2dFZjFqeDlOeVJyVUVMX0pn.webp",
    "Baronial Badge": "src/lib/assets/MissingItem.png",
    "Battle Bob": "https://stntrading.eu/img/-qLyd79lrqhHbrHqHeqLuTCt1KoE0XB8IqrVjjMyWs0/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFQmJRQXVYeFRnaHpCQ2dkcmxHT2F6Qk9FU25OOTdzTWdEalRJNXhsVi1aN1BpYVRJeUkxS2FXS1VOQ19GdXJWRzdYSFEzdTVabVY0R3pvLTFWZVJLdjZ0VTZpN3ZIdmc.webp",
    "Beastly Bonnet": "https://stntrading.eu/img/uEWJueQK7cfPCjKQOVJYCtpM0rsLplC7_ayLO7bGCc4/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZmUxVXVYaFBudlN4Q2dQZnVDUE9JTi13QmlkMHdxOEVNMjJWcXdsVXFadUhzWUdBekkxUEVXYVlIRFBSam9WSHFEM05nNmNZMUE0VG5wcjlRZlFYeDlOeVJuVUlWS3dF.webp",
    "Big Daddy": "https://stntrading.eu/img/xtonRvjzUg9iiKxi4D4HmPARjh7EOSuo-q4AMztvT04/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSlpUZ0dYQWpxc1RaRW5NZm9Ndi1ORy1zX2w5c240cFViaWpBNHdGUXBZdUxqWXpWakt3REhBdmNIWGFWczlsQzhDaVl6N0pjMkFJZnZwZXBSS3ctODRweUdiZWU5UHh1bzVB.webp",
    "Biomech Backpack": "https://stntrading.eu/img/ic-g1M205jVxsbsNTRTyLrWhBQ5Dz9qBYf94g2rg8XQ/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFS1pUZ1RVaF83aHpSQ21zX2pRNkdLQ3JOVnpkNHhzOFFNM1RNNWtsZF9NYkN6Tkc4LWNGMlhXZllPV0tGcTlsRzVXQ1JoN01JdFJObXg3bFAyV3FZ.webp",
    "Blind Justice": "src/lib/assets/MissingItem.png",
    "Boiling Point": "src/lib/assets/MissingItem.png",
    "Bolgan": "src/lib/assets/MissingItem.png",
    "Bolgan Family Crest": "src/lib/assets/MissingItem.png",
    "Bonk Helm": "src/lib/assets/MissingItem.png",
    "Brain Bucket": "src/lib/assets/MissingItem.png",
    "Brigade Helm": "src/lib/assets/MissingItem.png",
    "Brimstone": "https://stntrading.eu/img/CZLy2mIcvIQjSmwG_--rz2OFg8gOtDBZMbdINO4LUnY/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSmZnNGNUZ190dGoxOGdNbnlNdjZOR3VjRjFZaGt0OGRSaTJJNnhWY3BaYkd3YURNLUpWREVBX1VJRGEwN29sdnRDSFF4dmNGaEJJX2lvdUpJT1ZLNExnWjlxRlE.webp",
    "Brütal Bouffant": "src/lib/assets/MissingItem.png",
    "Buck Turner All-Stars": "src/lib/assets/MissingItem.png",
    "Bushman's Boonie": "src/lib/assets/MissingItem.png",
    "Camera Beard": "src/lib/assets/MissingItem.png",
    "Centurion": "src/lib/assets/MissingItem.png",
    "Champ Stamp": "src/lib/assets/MissingItem.png",
    "Cheet Sheet": "src/lib/assets/MissingItem.png",
    "Chief Constable": "src/lib/assets/MissingItem.png",
    "Cockfighter": "https://stntrading.eu/img/frFAEGSaqD2pAgDOMzkUhnx4ZyzNo-1CaPCAl_A-erw/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFS1lBc3VUaGp3c1RwOGhmZmlDUC1ETi13QmlkMHdxOE1GakdZNGsxQjZOZWJtTldGakkxR1hCS0VLQ19NNThsenBEM0l4N0o4eUFvUzFwcjVUZTEzeDlOeVJjVFRjcnVJ.webp",
    "Cold War Luchador": "src/lib/assets/MissingItem.png",
    "Combat Medic's Crusher Cap": "src/lib/assets/MissingItem.png",
    "Companion Cube Pin": "https://stntrading.eu/img/8q1M8VMb51zZHFiWaVwjTxIEfkdoLHM6paDJWFSmXKc/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFYlBqZ0JWQlhkdERsUmo4Mm9XUGVKV2JnQnk5OHh0c01BZ1dWcXdRVl9ZYk8wWXpNMUlnREdCUFFHWGZGczhsdTZXM0UzNm9seld0Q2lLVGpteVE.webp",
    "Company Man": "src/lib/assets/MissingItem.png",
    "Concheror": "https://stntrading.eu/img/GZj5FaahFOjFxTbT8mFhBy4wOx0OPgAVlnziMsvDEhg/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV4UVpVaHozdGdkVWlkcjJEUEdITi13QmlkMHdxOEVDMjJkcXdGa3BZTFhtWkdZMEpWR1JVNk5hRGFNLXAxSG9VU05qNlpNNkJkTGw5dTRGTFFYeDlOeVJ4WktLXzhR.webp",
    "Conjurer's Cowl": "src/lib/assets/MissingItem.png",
    "Conniver's Kunai": "src/lib/assets/MissingItem.png",
    "Conspiracy Cap": "src/lib/assets/MissingItem.png",
    "Crafty Hair": "https://stntrading.eu/img/1PZNErODI55hB8v-5Bp1l3Enitvv0sU2qPKaQFYZUgc/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFVGJ3Z2NZaDN1dVN4WGg5alpDUHlMQWU0Rm5zZ0s2WkZIM2pNbHdWUl9ZTGF4WXpKaWRGS1VWS0lNRGFJN29RMl9EM0ppN0pjeUFZT3lyN2hXTFFxOTRkT1FNSzVzYm9fdVI0a1pnQQ.webp",
    "Criminal Cloak": "src/lib/assets/MissingItem.png",
    "Croft's Crest": "https://stntrading.eu/img/EVqtqdZGJukeO6991uANWJha05tvuQYff3kn2pj4GZY/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZll3b1RZaG5qdkQ5R3Q4VG5IX1dKUnJWUW45dzI0SlJRMzJJOHhnSXNOdWZrWW1WaklWMlNVdlFLV3FRNW9RbTdDbll3djVjeVVkVDQ1N1VCRVRNSVo5QQ.webp",
    "Cross-Comm Crash Helmet": "https://stntrading.eu/img/uJUfXjhun5OmAqJtZmO6cF5_wJ7UwT2ymDTsjMyosBE/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFTWZnRUNZZ2p0dER4S2pkclpBZk9lRC1WT3pZbG52SlFDaXpRX3lGVXJaclhzYVRNM2NWS2FVZlJmQ3FKcDlWeTREQ1JydnNZM1ZkYTFwUFVXSjF1OWF1Nlg5dw.webp",
    "Cross-Comm Express": "https://stntrading.eu/img/I1xQZuoLYt0jIlF1AR1VX7MySg0TOv6hi-rfisq7zYE/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFTWZnRUNZZ2podHkxWHQ4VG5IX1dKUnVOUXo5c3c1SklNMm1Ob2tGVl9ZckxtYVc1aEpsS2JVcU1NWGFSb3JWM3ZEWEJydnNVd1VJXzQ1N1VCTU5oYUxONA.webp",
    "Crosslinker's Coil": "https://stntrading.eu/img/2AY7uWcD90vkk2Q5f8M0P7lCyXIyCKhxLCsBfT5gPcM/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFTWVRa0JVaExzckR0TWdjVHVET2F6Qk9FU25OOTdzc1ZSMzI5dXh3SXROZUMyTm1Ca2MxZkFWYUpiWF9ZOHBBNjVEWDVsN1pabUE5WG5wTzhIZnhLdjZ0WDIyQTlyTXc.webp",
    "Crown of the Old Kingdom": "src/lib/assets/MissingItem.png",
    "Dadliest Catch": "src/lib/assets/MissingItem.png",
    "Dashin' Hashshashin": "src/lib/assets/MissingItem.png",
    "Dead Cone": "src/lib/assets/MissingItem.png",
    "Deadliest Duckling": "https://stntrading.eu/img/iQeD8ClOQmCNIVG7EnQPdo7BbmTdti7jOSQsxB7as40/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFRFlUZ1ZTQmpwaHp4R2hjZlpBZk9lRC1WT240SXc1c0VIaldGdHdRY29OYnZuWWpRLUlWM0dCNlJiRDZWcTlneTRVWFJodXBVNkFOTGhwdlVXSjFzT2ZFYWZJUQ.webp",
    "Der Maschinensoldaten-Helm": "src/lib/assets/MissingItem.png",
    "Deus Specs": "src/lib/assets/MissingItem.png",
    "Diamondback": "https://stntrading.eu/img/-CvfEiEqWN_HBDnXWUeaCQl8r24K5ZHPzYYaCPLGpwQ/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV3TVVSU1R3dlM1TWhON2pIODJBQ2ZJSG5wUm12SkZVZ0dCdXdnVXNNTERqYUc0X0lsZWJWcUlIV2Zadm8xQzZDbk0ydXNJMkROSGs5dWxTWjB5eDQ5dmZUYnVT.webp",
    "Die Regime-Panzerung": "src/lib/assets/MissingItem.png",
    "Distinguished Rogue": "https://stntrading.eu/img/fUzL90u9BFu_ZLqlVg8vl-DZ1_78bnVHBpjXrp2OMgM/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZmV6Z1NVaHIyaHl0VGtmZnFET0NMRGE0R21ZNWdzOElNaWpRenlRSl9ackhrWVdWbUsxYVVCNlZZV2ExcThWbnBDSEkyN1o5aUFJX2h1YXNJTHUxTTkzYzc.webp",
    "Doe-Boy": "https://stntrading.eu/img/VjV59nYHeGOzaLYBNh1agETa8zxsIiJgpZUmkmkTz7s/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSlpRZ3VUaFR1dkRGR212ZmdBdWVDRE9VU2lPVTU1SUpTM0hob3hnTl9OcmJpYURVM0tsM0JCS0lJRF9BLW9BdTVXM1JodjVCZ0FJSGs5ZWxXZkYtLTVkZkJMZkJ5WjN4VHhNSzc.webp",
    "Doublecross-Comm": "https://stntrading.eu/img/U6m6J4yh5biUvRdWjvqAA60gatUaaxD0hiTiUiD6DUI/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFTWZnRUNZZ2pzc1NoR212ZnFET0NMRGE1WHpJeG1zOGxSMm1kcHcxTjlZcmZuWW04X0lBTERVZk1HQ0tadjhGX3VYM1kwNlo5bkF0VGd1YXNJTG4xZXY3OVY.webp",
    "Dragonborn Helmet": "https://stntrading.eu/img/OXLwpsCKqs8J46tF8WZFx0ZfyH_IdeNcfopIDZws_yE/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFWVp4NERWQmJkc0QxUGhjM3lNdjZOR3VjRjFZa3pzc01Dam04X2tsUjZNYkxrYVRZeElWZkFXZlFJREtKdHJWMi1XbkkyNjU1bEJZRHU4ZUpJT1ZLNEpaNFByMEk.webp",
    "Dread Hiding Hood": "src/lib/assets/MissingItem.png",
    "Dread Knot": "https://stntrading.eu/img/bYzuLN5JHpzHJG-X8-ZikTsJYApLcPjGfeMb6bm1S8M/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFRGFRWUhSQ1R4c0RkRW5jYlpHZjJjQS00UGotVTU1SUpTM0hnOHdGVXZackMyWW1RMUl3TEFWS0pmQ0sxcHJBNjlYM0JydnBGbUJOVGhvLWxVTFE3bXNvREFMZkJ5Wi1zVG44Q00.webp",
    "El Jefe": "src/lib/assets/MissingItem.png",
    "Engineer's Cap": "https://stntrading.eu/img/Ak_JvMUE1bpyRl4KsUEX02zX4oq_Gj3z_-nCoLS0_Yw/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFT1lnQVlVeDducWdkWG1zbnZBODJFQ2ZRX2w5c240cFViMnpOcGtnTXRaYlRuTldKbUtsREJCX2dPRFBGbzlWbTRDaVJyc01RelVvR3o5cjFTTFFubzRKeUdiZWVvNG1qWEZ3.webp",
    "Faerie Solitaire Pin": "src/lib/assets/MissingItem.png",
    "Fan O'War": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIUxQZUhz3tgdUidrgDPyzBOESnN97ssRTi2AywgcqNbDjaDIyK1yWAvcNCqZspl-0UXRjuZ83Bta08ukDLRKv6tVfpQ3ziw/360fx360f",
    "Fear Monger": "https://stntrading.eu/img/ouIWP6eEtIWBEPdh98K7eJnb8RiYc5k1FX1K6iD0s_c/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSmJRd3VXeDdqcWdkT2g4YmhDT0N6Qk9FU25OOTd0c0FCampBNHhsbDZiZWUwWUdRMElnS2FCUFFIQ3FVNDlWdnZVSEZqdjVJN1VZUGpwdXRTTHhLdjZ0VXFiUXA0RUE.webp",
    "Firefly": "https://stntrading.eu/img/tdiJt-B-BzFhMYCVtVp8-nFfn_NyKtQ6xw-OBUXGHrg/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSmJRd3VXeEx3dlQ1UGtmZnFET0NMRGE0Rno5eGo1OFpUaURWdHcxSjViZUhuYVRFeUlBR1NXS05kRGZFN3BGM3FYM2RqdWNSZ0E5VzN1YXNJTGxBYnRuQkQ.webp",
    "First American": "src/lib/assets/MissingItem.png",
    "Flying Guillotine": "https://stntrading.eu/img/dFaVe47_HhfB4vu0Rg4BRoR41AU3HVu_gveEbOzGy5w/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV4UVZZaGp1dlRsVmpkclpBZk9lRC1WT3lOeHM0OFZUanpjN2tGbDROclBoWkRGaUlWMmJVYVFHV0sxdjkxMjRXaVl6dXBJekROUzNvZlVXSjF2emhkbHZOQQ.webp",
    "Foppish Physician": "https://stntrading.eu/img/QwPD_91_LIPmOYwNJjTCp3H4SfE-ecAAkiqKvuBr4AU/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZmV6Z1NVaHIyaHpWR2pNSGxNdnlKQy1zVWt0OEs2WkZIM2pNbGxWUXJaYnZrTkc4eWRGWEFXZkVJQ3FGanAxNjBDQ05pdlpJM1ZZX2o5dThEZkE2LXNZU1VONjVzYm9fVTdvM3FLdw.webp",
    "Fortified Compound": "https://stntrading.eu/img/4fhavdSJvaROJ9VY-Qte7rFcdtVIyMNNFBvwTY668gE/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV3VWVTaVQyc0RGR2p2ZnFET0NMRGE1U21vSmw0OElFaUdBOXhGY2lON3JnYURKa0t3Q2FWUEpmQzZJLXBGNjBEeVUzdnNGbkFvVGp1YXNJTGdWd3BjdU8.webp",
    "Fortune Hunter": "https://stntrading.eu/img/1FkR2td7q0FLnE5yAGHN1avoUwZrCKPyB5OuHzhbifI/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZll3b1RZZ3ZydXpOOGpNM3JBczJBQ2ZJSG5wUms0OFJVMm1kb3lWY3FNTE8yWW1WaGNRTEFCZlFHQzZWcThWQzlXM0JpdmNSaURZTGxyLXBTWjB5eDQ1a3hPYVI0.webp",
    "Freedom Staff": "src/lib/assets/MissingItem.png",
    "Friends Forever Companion Square Badge": "src/lib/assets/MissingItem.png",
    "Geisha Boy": "src/lib/assets/MissingItem.png",
    "Gilded Guard": "src/lib/assets/MissingItem.png",
    "Glengarry Bonnet": "src/lib/assets/MissingItem.png",
    "Grandmaster": "https://stntrading.eu/img/72McQ-gC0FTRCP1L39f64eElDBRr5hf4r-vCjWowpG0/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVpBSUNUaVRxdVN4OGhNbjBDdmZDRHJZQnlvZzB0OEZYaW1FX3dWZ3FZTEMwYUdRMGNBZkdXS0VPWHZZN29WMjVEeVpxdnBZelZwbW0tYndJbzRycnhB.webp",
    "Grizzled Growth": "src/lib/assets/MissingItem.png",
    "Half-Zatoichi": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIUxQZUhz3tgdIidznA_OzBOESnN97sJEHiDI6xFIvY7HlMTMwIlXDUPBbWvA_8lq9CyY3uZUyA4fvp-sCcRKv6tUa3lr7Jg/360fx360f",
    "Ham Shank": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIUw8QUCTuuSpEjYa-VKuOXrRUytszsZYA3GM9yVh9MbDlNmAwIweQV_dbC_ZorAy1XnBrptdtU4darXRp/360fx360f",
    "Hardy Laurel": "src/lib/assets/MissingItem.png",
    "Heavy Artillery Officer's Cap": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIYw8uVR7jriFLidzZAfOeD-VOn9w35pIBgGQ7wFR-YOW3MzI1JgbEAKIPD6FjrVq9CCZjsJFgV4_jp_UWJ1v-tW4G0w/360fx360f",
    "Hero's Hachimaki": "src/lib/assets/MissingItem.png",
    "Hero's Tail": "src/lib/assets/MissingItem.png",
    "Heroic Companion Badge": "src/lib/assets/MissingItem.png",
    "Hetman's Headpiece": "src/lib/assets/MissingItem.png",
    "Hitt Mann Badge": "src/lib/assets/MissingItem.png",
    "Horace": "src/lib/assets/MissingItem.png",
    "Human Cannonball": "src/lib/assets/MissingItem.png",
    "Huo-Long Heater": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIUwQQUw_ttgdPidrhCLyNXOQFnY1stcgHiGE-yVkrNbLlaGFhd1LDV6FfBaY8oVvqW3Fqv5QxGse48Kc60DPZ/360fx360f",
    "InfoShow TF2 Tournament Participant": "src/lib/assets/MissingItem.png",
    "Janissary Ketche": "src/lib/assets/MissingItem.png",
    "Jungle Booty": "https://stntrading.eu/img/TtBMyZXOsS5vq9_VPgYo7kvhMz6-aPjpDpetwnpoeRM/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZmZqZ2JTQlhsdEQxOGlzZnBHZXV6Qk9FU25OOTd0OFJSajJGdmxGRXZaT2JzYUdSaEpRV2JVUEJkRHFOb29WcTVXM1F6dVpObEF0WHVvZU5YZlJLdjZ0WHlZOHFpYUE.webp",
    "K-9 Mane": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEKZTgCTRrhvTBGhMXjGc2ACfIHnpQwsMhWiDRtw1h-bbDmaTRmIQfDV6YICaM-91DpXSQ065Y0BtPjpbpfZ0yx45GbrIXs/360fx360f",
    "Killer Exclusive": "https://stntrading.eu/img/7GIDRCQY70Ka3FpeD2A5ENsT51rF2jF4u-rt4V3Crlw/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFYmJ3QXVWUnIyaHoxTmo4SG9DUGVlTi13QmlkMHdxOGtOajJRLWsxZ29ZYkhqTXpJMGR3TEhWS0ZmWDZFOHBsenFESFl3dUpSbUFZYnZvT3dIZVZyeDlOeVJXbHNOVGRF.webp",
    "King of Scotland Cape": "https://stntrading.eu/img/KyFG9NZMR6at8k9QgA9Sk6ZsoUuHWLoSYVRbDf27EYw/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZmV6Z2FWQlhsdXpsVGpmZnFET0NMRGE1VnpkeHQ0Y1ZVM1dKdnlGWXBNTGJoTkRRMWN3V2JWNk1KQ3FRNDlnenFDbmMwdU1KaEE0Ymx1YXNJTG9Vem40MmE.webp",
    "Lacking Moral Fiber Mask": "src/lib/assets/MissingItem.png",
    "Last Straw": "src/lib/assets/MissingItem.png",
    "Little Bear": "src/lib/assets/MissingItem.png",
    "Lone Star": "src/lib/assets/MissingItem.png",
    "Machina": "https://stntrading.eu/img/MfrsKBsaDhE8qJ5REscQCYsT6iSBXahKa_DPPVg0yWc/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV3TVVSU1R4dGpGVGpkcjBCUFNBRGQ4TW1zZ3k0TjVRMm1jN3d3TjVOdVhpYUdNMUlGZVdVS05hV3ZFOG9ndm9EeUpodjVkbFVOV3o4LWtEZWdXN3FzS1laRG9mV0N3Yg.webp",
    "Map Maker's Medallion": "src/lib/assets/MissingItem.png",
    "Mappers vs. Machines Participant Medal 2017": "src/lib/assets/MissingItem.png",
    "Mark of the Saint": "src/lib/assets/MissingItem.png",
    "Marxman": "https://stntrading.eu/img/ZEMs-G0-T1e5-nS4AnvRxDdAbspatMV1Db4J5fB1VHo/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFWWFEZ1dVUnJ4cXoxUXQ4VG5IX1dKUnJCUndvSXo0OGNHajI4eWxWY3FiYkN6TkdRMmNRYkdVZlJZQ2FCcW9RN3VDeVpndko0MFZ0YjQ1N1VCUnltUWRQTQ.webp",
    "Mask of the Shaman": "https://stntrading.eu/img/TOma5LuCfxBKvM_z8DyrLY3JFYnlebekTrAt1CUruD8/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFUGVSUUZZaGJqcXpOOGhNbjBDdmZDWExGVXlOZzJ0NU1CMzJBLXhnY3RNYkhpWW1jMUlGeVJWNklLWGFkdG9GN3VEM0prNnNFekE1bW0tYnh4bEdCbnln.webp",
    "Master's Yellow Belt": "https://stntrading.eu/img/EYsLMEeh1FOoRBZdQR1TG_wYBRT17e8z9uQyPLXVjMQ/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFQmJSVVFTUjdkc0QxQ2pNcm5BX2F6Qk9FU25OOTc1TUFGakRJOWtBTWpOdUt4YUc5aGRseVJWX2NNQ19kanJRdV9EU1pndkpVd0FvT3lwdU5YS3hLdjZ0V2RuMHBabWc.webp",
    "Maul": "src/lib/assets/MissingItem.png",
    "Menpo": "src/lib/assets/MissingItem.png",
    "Merc Medal": "https://stntrading.eu/img/lF02OCIwCc22ID3HmoqKiiw4xQOclCkZLsD71UrqiJY/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFQmJRQXVYeHJtdnoxOGhNbjBDdmZDVzdFR25kczA0WkpUaW1WdWwxZDVZTE94WTJjeGRGUEhWS1ZiQktkajhBMjhDbll3c1pJMEI1bW0tYnpia05wNnhn.webp",
    "Merc's Pride Scarf": "https://stntrading.eu/img/7Xll-ksPvmxVWpygPoN-XiMvBtdMzWRThh5hsSZ03u8/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFWWJ3WURXeVR4dHp0QWpkclpBZk9lRC1WT3pJb3p0OFlOMzJNeXdGbDZZN2EwWlc0MWNWU1FXZklJV2F3XzhsdnFXaUpoNjVOblZ0THU5dlVXSjFzeDFScVB4Zw.webp",
    "Mister Bubbles": "https://stntrading.eu/img/_6hyiVp3AJtK_otw1e_L_iSQiaOcZeEYE-vG3tGinYs/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSlpUZ1RWQnpkdkRsSGpOSFpDZjJBQk44TW1zZ3k0TjRCM0RCcHdBUjRZTEd3WjJkamR3R1JBX1JZV3FFNzhncTdVQ1V6dThFd1VZZm5vYjhITHdfdXFzS1laTy0tLVRUVw.webp",
    "MK 50": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEKZTgCTRrhvTBGhMXjGc2ACfIHnpQwsMhWiDRtw1h-bbDmaTRmIQfDV6YICaM-91DpXSQ065Y0BtPjpbpfZ0yx45GbrIXs/360fx360f",
    "Nabler": "src/lib/assets/MissingItem.png",
    "Nanobalaclava": "https://stntrading.eu/img/lwforx05Ss_CRkM1Z9tL6bRsHPyqrxYVVj5Y7xDqRRc/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFUGFSOHVYeDd1dEN4TW44MzBNdjZOR3VjRjFkOWxzOFlCMkdFN2sxWl9NTGEzTkdBX2MxZkVCUFFLQktNNzhneThYaUkwNnBNeUFvRGhydTFJT1ZLNEVUMk5ENEU.webp",
    "Neon Annihilator": "https://stntrading.eu/img/YBKzs5yWTzcxO9qonLAfL6WN_p2p69EuBIZhw2ME66M/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV4UVZZaFhudHpaUWdjX29NdjZOR3VjRjFkOWo0OGdHaTJBLXh3Y3BaTGEyYUROaGRnR2FXZmxiQktVN3JGNjZESEF4dXBSbEROVHVwZUpJT1ZLNDhfYnpkbWM.webp",
    "Noh Mercy": "https://stntrading.eu/img/DnDn_4nOOtkIzfJHFgMVRJViE-MR_a_Wbg8izXw8lJo/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFWVpBZ1dTQlhkdGpGTmdzbnJET0dITi13QmlkMHdxOEZXMmpWdndGaF9NZUd3TkRZMkt3R2JWdlVMWDZRNHBGcS1YWEZuNlpZMkE5T3dydTlYZUE3eDlOeVJjOXA2djdj.webp",
    "Noise Maker": "src/lib/assets/MissingItem.png",
    "Nostromo Napalmer": "src/lib/assets/MissingItem.png",
    "Officer's Ushanka": "https://stntrading.eu/img/tFzT93lNN3yF2Q9hsR_I3_KEcNKGzBK5r10KYUDA9VE/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFRGFRWUhSQ1QzcXpCQ2hzUG5NdjZOR3VjRjFkeGt2Y1FCaVRBLXhBUjVZT0xqWURNeUlseVFCYVJkRFBScnJRbS1DaUUydjVZNlVOSGg5ZXhJT1ZLNEdBWWFJUzA.webp",
    "Original": "https://stntrading.eu/img/m94mKe6LlXEu1KZoZQP2zIF8p84LkuqDWnr8I9bmiLg/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV3VVVTU1R3dHp0SWpkenFET2VDQy1nRmllVTU1SUpTM0hnOGtnY3JaTHZnWjJjMkpsT2JWUFlOV2FjX28xMi1XQ0puc2NabkJJWGtycjlUS2wyOXRJcVNMZkJ5WjYxTnFqRDY.webp",
    "Otolaryngologist's Mirror": "https://stntrading.eu/img/0sBnBb0Sq-K55DUBQKpmBevYzrjglg5Oo5wX0aJodMo/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFR2FRTVlYaVR2c1NwUmg5clpBZk9lRC1WT3lJcGd0Y2NDakRBLWxRUjVZN1hoTTJSaGNWV1FXZkJjQ2FOcG9sLTZYWEptc01ZMkJZWHVyX1VXSjFzTFdNaHZIUQ.webp",
    "Person in the Iron Mask": "https://stntrading.eu/img/X0raiIgG0gGTcrAsvR0fTxoatUc2ARiy08yP1gc9ZHE/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSlpRZ3VXeEx3dlRWQ2h2ZnFET0NMRGE1UXk0aGlzc2RUMnpjX3cxVXRNdVhpWUdGbEkxSEdVNkZkQmF4ajhndTRYblpnN2NVN0JZZXd1YXNJTGt3V1ppaEc.webp",
    "Philanthropist's Indulgence": "src/lib/assets/MissingItem.png",
    "Pilotka": "src/lib/assets/MissingItem.png",
    "Pip-Boy": "https://stntrading.eu/img/dWfsI0tKY-66BiS6HrnJW81zGNbC2oTen59oqc4Y7Ps/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSmFSTXVUUm5kdERsUmo4Mm9YcURmVy1GU3k5dzA0Y1ZRMnpCdGtnY3VadWZzTVdjMGNBZWFVUEJmV2FSdHAxMjlEU0V4c0lseld0QkhvZ1VseGc.webp",
    "Planeswalker Goggles": "https://stntrading.eu/img/1hYpSNqXd8GMeadSI2grX36aKepAejGKO8cIfJquJfg/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFWWJ3Z0VTU1R2ckQ5OGhNbjBDdmZDV3VRRW50NDN0SllBaW1ZNGxGSXZaYmV6WTJjMkpsV1NVcUlPRF9kdG9WRzRXU0l4dWNNd0RKbW0tYnhCbTVDMVR3.webp",
    "Planeswalker Helm": "src/lib/assets/MissingItem.png",
    "Point and Shoot": "https://stntrading.eu/img/MZJzOEpbnA8xnAKOjnL8d31E-m2cIEhPADB6dzTAGic/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZmZna3VTaEw0aHpCQ25QZmlDUC1ETi13QmlkMHdxOEFNajJScXhRQXNON3JtWm1Bekp3YVVXZkVMV3ZOdDlRMjhXaUV4N0o5bEJ0TGo4cmtIS0FyeDlOeVJrWmV1RDhr.webp",
    "Potato of Labor": "src/lib/assets/MissingItem.png",
    "Pounding Father": "https://stntrading.eu/img/aY-cP5qdyie6_waYx7Jq84-C1blNUIO_WiiiE2-znEA/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSlpRZ3VWUjdqcmlGOG44SGhNdjZOR3VjRjFZNW01TUZXZ1c4NXdRQl9OZVhsYVdVM2RGR1NVUFVLQ3FVNHBGLV9DbkZrN3A1bVVvUG1vdTVJT1ZLNHRoeE9fNVE.webp",
    "Prinny Hat": "src/lib/assets/MissingItem.png",
    "Prinny Machete": "src/lib/assets/MissingItem.png",
    "Prinny Pouch": "src/lib/assets/MissingItem.png",
    "Prize Plushy": "src/lib/assets/MissingItem.png",
    "Professional's Panama": "src/lib/assets/MissingItem.png",
    "Professor's Pineapple": "src/lib/assets/MissingItem.png",
    "Public Accessor": "src/lib/assets/MissingItem.png",
    "Purity Fist": "https://stntrading.eu/img/pN5XaPS2ju0V1gRxA9nCBWN5htueggxK7ojaMWu0ras/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFUGFSOHVUaHJ3c1Q1Q21zWFpBZk9lRC1WT21Oa3g0Y1lGaVRNOWtnQXVNckhtWldjMUsxR1dWdmdKRFBCdDlRMl9YM2RpNjhReVZkV3lvZlVXSjFzQlBFekpxQQ.webp",
    "Quadwrangler": "src/lib/assets/MissingItem.png",
    "Quäckenbirdt": "https://stntrading.eu/img/QIxitmgmuvlrZIcs5laoBTbqB-dfrms9aS-z59uGoxs/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFZFV3OGNZZ3pqckR0THQ4VG5IX1dKUnVKVm1keG41c0FDM3pRNXlWa3BOLUxuTlRFd0lWM0RCX0FKV2EwNThWRzVDblF6dThJekI0YjQ1N1VCbDdCVkRRUQ.webp",
    "Red-Tape Recorder": "https://community.akamai.steamstatic.com/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIUxQVYgjjqChGmvfqDOCLDa5WzIM3vcMN3WMywlUiNrK2aW8-KwCXUKFcBfNtpwnpXn40u5diUdW1uasILvCuI-ur/360fx360f",
    "Respectless Rubber Glove": "https://stntrading.eu/img/-0T7wRkD7SWxFnjv21we-E1EbQVmg7YZ4GIwjFNrkOM/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFYmRSVWVZaGpxc1R0SWpjYlpBZk9lRC1WT3lOaHN2SllFM0RKdXlWTXZiTFRuWW1aaWNWU1hBcVFJV1BGcDhsdTRXbk13c1pVeUJZZmlwUFVXSjF2UUlmQUNSdw.webp",
    "Righteous Bison": "https://stntrading.eu/img/BCIljAE15_ml07gZTEWYX6_Wp3VpLhSfadK9L2Z0qII/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV3TURXaVR3c1Q5TG5NM3BHT0dPQWZNUGxlVTU1SUpTM0hnNncxTjVackN6YVRSa0tsS1hWZmNJQ1BOc29RbnRYeVppNnBJeEF0TzA5ZWtIY0F6bTRkYVhMZkJ5WjVSZ0p0QmY.webp",
    "Robo-Sandvich": "src/lib/assets/MissingItem.png",
    "Robot Chicken Hat": "src/lib/assets/MissingItem.png",
    "Russian Rocketeer": "src/lib/assets/MissingItem.png",
    "Samur-Eye": "src/lib/assets/MissingItem.png",
    "Scotsman's Stove Pipe": "src/lib/assets/MissingItem.png",
    "Scrap Pack": "src/lib/assets/MissingItem.png",
    "Sharp Dresser": "src/lib/assets/MissingItem.png",
    "Sharpened Volcano Fragment": "src/lib/assets/MissingItem.png",
    "Short Circuit": "src/lib/assets/MissingItem.png",
    "Shred Alert": "src/lib/assets/MissingItem.png",
    "Siberian Sophisticate": "src/lib/assets/MissingItem.png",
    "Sign of the Wolf's School": "src/lib/assets/MissingItem.png",
    "Spycrab": "src/lib/assets/MissingItem.png",
    "Stahlhelm": "src/lib/assets/MissingItem.png",
    "Stainless Pot": "src/lib/assets/MissingItem.png",
    "Steel Sixpack": "src/lib/assets/MissingItem.png",
    "Steel Songbird": "src/lib/assets/MissingItem.png",
    "Stovepipe Sniper Shako": "src/lib/assets/MissingItem.png",
    "Sun-on-a-Stick": "https://stntrading.eu/img/hAvU8selVZ-usGV4I51mX9Y-zfbbLrANWp0L9vyG4XM/aHR0cHM6Ly9zdGVhbWNvbW11bml0eS1hLmFrYW1haWhkLm5ldC9lY29ub215L2ltYWdlL2ZXRmM4MmpzMGZtb1JBUC1xT0lQdTVUSFNXcWZTbVRFTExxY1V5d0draWpWalpVTFVyc20xai05eGdFSVV4VVlXd19kdmpGUmpmZnJEUEdKTi13QmlkMHdxNU5YMjJNLXhnUi1aYkhnTW1Ca0pnR2JVZlVHQ3FWb3JGaTBVSDVqc0pZMEFOYTFvZUpmTDFfeDlOeVJTNTkzUUxV.webp",
    "Supreme Strategist's Sigil of Status": "src/lib/assets/MissingItem.png",
    "Sydney Straw Boat": "src/lib/assets/MissingItem.png",
    "Tartan Shade": "src/lib/assets/MissingItem.png",
    "Tartantaloons": "src/lib/assets/MissingItem.png",
    "Texas Ten Gallon": "src/lib/assets/MissingItem.png",
    "TF2VRH": "src/lib/assets/MissingItem.png",
    "That '70s Chapeau": "src/lib/assets/MissingItem.png",
    "Three-Rune Blade": "src/lib/assets/MissingItem.png",
    "Tomb Readers": "src/lib/assets/MissingItem.png",
    "Tomb Wrapper": "src/lib/assets/MissingItem.png",
    "Top Notch": "src/lib/assets/MissingItem.png",
    "Tough Guy's Toque": "src/lib/assets/MissingItem.png"
};


